import { Producto } from '@/types/ecommerce'

export const DEMO_PRODUCTS: Producto[] = [
    {
        id: '1',
        sku: 'FND-IPH15-001',
        nombre: 'Funda MagSafe Premium iPhone 15 Pro Max',
        descripcion: 'Funda de silicona premium con soporte MagSafe integrado. Protección de grado militar con acabado suave al tacto.',
        tipo: 'funda',
        marca: 'Apple',
        marca_compatible: ['iPhone 15 Pro Max'],
        precio_venta: 1890,
        moneda: 'UYU',
        stock_actual: 15,
        stock_critico: 5,
        es_repuesto: false,
        es_venta: true,
        imagen_url: '/products/funda-iphone.png',
        imagenes_adicionales: [],
        activo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '2',
        sku: 'CRG-USB-20W',
        nombre: 'Cargador USB-C 20W Carga Rápida',
        descripcion: 'Cargador de pared ultra rápido compatible con todos los dispositivos USB-C. Certificación MFi.',
        tipo: 'cargador',
        marca: 'Genérico',
        marca_compatible: ['iPhone', 'Samsung', 'Xiaomi', 'Motorola'],
        precio_venta: 990,
        moneda: 'UYU',
        stock_actual: 28,
        stock_critico: 10,
        es_repuesto: false,
        es_venta: true,
        imagen_url: '/products/cargador-usbc.png',
        imagenes_adicionales: [],
        activo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '3',
        sku: 'VID-SAM-S24',
        nombre: 'Vidrio Templado Samsung Galaxy S24 Ultra',
        descripcion: 'Protector de pantalla 9H con bordes curvos y anti-huellas. Instalación sin burbujas.',
        tipo: 'vidrio',
        marca: 'Premium Glass',
        marca_compatible: ['Samsung Galaxy S24 Ultra'],
        precio_venta: 790,
        precio_anterior: 990,
        moneda: 'UYU',
        stock_actual: 3,
        stock_critico: 5,
        es_repuesto: false,
        es_venta: true,
        imagen_url: '/products/vidrio-templado.png',
        imagenes_adicionales: [],
        activo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '4',
        sku: 'CAB-USBC-2M',
        nombre: 'Cable USB-C a USB-C 2 Metros Trenzado',
        descripcion: 'Cable reforzado con trenzado de nylon, soporta carga rápida hasta 100W y transferencia de datos a 480Mbps.',
        tipo: 'cable',
        marca: 'TechCable',
        marca_compatible: ['Universal'],
        precio_venta: 590,
        moneda: 'UYU',
        stock_actual: 45,
        stock_critico: 15,
        es_repuesto: false,
        es_venta: true,
        imagen_url: '/products/funda-iphone.png',
        imagenes_adicionales: [],
        activo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '5',
        sku: 'AUR-TWS-PRO',
        nombre: 'Auriculares TWS Pro Bluetooth 5.3',
        descripcion: 'Auriculares inalámbricos con cancelación de ruido activa (ANC) y 32hs de batería total con el estuche.',
        tipo: 'auricular',
        marca: 'SoundPro',
        marca_compatible: ['Universal'],
        precio_venta: 2490,
        moneda: 'UYU',
        stock_actual: 8,
        stock_critico: 3,
        es_repuesto: false,
        es_venta: true,
        imagen_url: '/products/cargador-usbc.png',
        imagenes_adicionales: [],
        activo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '6',
        sku: 'FND-XIR-N12',
        nombre: 'Funda Silicona Xiaomi Redmi Note 12',
        descripcion: 'Funda de silicona suave con protección de cámara y forro interior de microfibra.',
        tipo: 'funda',
        marca: 'Xiaomi',
        marca_compatible: ['Redmi Note 12', 'Redmi Note 12 Pro'],
        precio_venta: 690,
        moneda: 'UYU',
        stock_actual: 12,
        stock_critico: 5,
        es_repuesto: false,
        es_venta: true,
        imagen_url: '/products/vidrio-templado.png',
        imagenes_adicionales: [],
        activo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '7',
        sku: 'CRG-WIRELESS-15W',
        nombre: 'Cargador Inalámbrico 15W MagSafe',
        descripcion: 'Base de carga inalámbrica magnética. Carga tu dispositivo solo con apoyarlo.',
        tipo: 'cargador',
        marca: 'Apple',
        marca_compatible: ['iPhone 12+', 'Samsung S20+', 'Universal Qi'],
        precio_venta: 2290,
        precio_anterior: 2690,
        moneda: 'UYU',
        stock_actual: 6,
        stock_critico: 3,
        es_repuesto: false,
        es_venta: true,
        imagen_url: '/products/cargador-usbc.png',
        imagenes_adicionales: [],
        activo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '8',
        sku: 'VID-IPH15-PRV',
        nombre: 'Vidrio Privacidad iPhone 15 Pro',
        descripcion: 'Protector anti-espía con filtro de privacidad 180°. Mantiene tu información segura de miradas curiosas.',
        tipo: 'vidrio',
        marca: 'Premium Glass',
        marca_compatible: ['iPhone 15 Pro', 'iPhone 15 Pro Max'],
        precio_venta: 1290,
        moneda: 'UYU',
        stock_actual: 18,
        stock_critico: 5,
        es_repuesto: false,
        es_venta: true,
        imagen_url: '/products/vidrio-templado.png',
        imagenes_adicionales: [],
        activo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
]
